### ISSUE TITLE
Missing spring holes in grips

### ISSUE THREAD

**Issue by jengo** [Sillybutts/Alchemist#5]
I started to assemble my blaster, when I realized the spring hole in the grips is missing from the STLs.  The top grip in the image is from the files directly in the .zip file from git.  The bottom grip was printed after I exported from the "Files for designers".  Additionally, the "files for designers" doesn't appear to be updated since 2023/11/11.

Also, what is the difference between the "files for designers" plain and blank template versions ?  I can't seem to find the difference between the two.

![IMG_0043](https://github.com/Sillybutts/Alchemist/assets/1064021/f518c95d-a955-404d-8e9d-602b2959d9b8)

**Comment by jengo** [comment]
It appears that the trigger is also missing the spring slot from the STL in git, had to export it

**Comment by Sillybutts** [comment]
The spring there has been removed in the most recent versions of Alchemist. 

It's only purpose was to make the trigger lighter. 

However, it appears that many people have poorly tuned printers, to the point where the tolerances make this extra spring trip the sear prematurely. 

Ie, for some people, this spring makes the blaster not work correctly. 

So, since it was only an optional piece, I've fully removed it for everyone to prevent issues.
